apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-python-app
  labels:
    app: demo-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-python-app
  template:
    metadata:
      labels:
        app: demo-python-app
    spec:
      containers:
        - name: web
          image: docker.io/989988/demo-python-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080   
          env:
            - name: PORT
              value: "8080"
            - name: PYTHONUNBUFFERED
              value: "1"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: demo-python-app
  labels:
    app: demo-python-app
spec:
  type: ClusterIP
  selector:
    app: demo-python-app
  ports:
    - name: http
      port: 80
      targetPort: 8080   
